int _putchar(char c);
struct dogi;
char *name;
float age;
char *owner;
void init_dog(struct dog *d, char *name, float age, char *owner);
void print_dog(struct dog *d);
struct dog;
dog_t *new_dog(char *name, float age, char *owner);
void free_dog(dog_t *d);
